include:
  - '.cicd/kaniko.yml'
  # - '.cicd/go-build.yml'
  - '.cicd/go-test.yml'
  - '.cicd/image-exists.yml'

stages:
  - prep
  - build
  - test

variables:
  CI_OCI_REGISTRY: "public.ecr.aws/nolus"
  AWS_REGISTRY_ID: "013603813222"
# https://github.com/GoogleContainerTools/kaniko/issues/1542#issuecomment-853929795
  container: "docker"

  NOLUS_BUILDER_REPO: "builder"
  NOLUS_BUILDER_TAG: "0.2"
  NOLUS_BUILDER_IMAGE: "${CI_OCI_REGISTRY}/${NOLUS_BUILDER_REPO}:${NOLUS_BUILDER_TAG}"

  NOLUS_NODE_REPO: "node"
  NOLUS_NODE_TAG: "0.1"
  NOLUS_NODE_IMAGE: "${CI_OCI_REGISTRY}/${NOLUS_NODE_REPO}:${NOLUS_NODE_TAG}"

  NOLUS_INTEGRATION_REPO: "integration"
  NOLUS_INTEGRATION_TAG: "0.9"
  NOLUS_INTEGRATION_IMAGE: "${CI_OCI_REGISTRY}/${NOLUS_INTEGRATION_REPO}:${NOLUS_INTEGRATION_TAG}"

#ref: https://github.com/GoogleContainerTools/kaniko
prep-builder:
  stage: prep
  needs: []
  variables:
    IMAGE_REGISTRY_ID: ${AWS_REGISTRY_ID}
    IMAGE_REPO: ${NOLUS_BUILDER_REPO}
    IMAGE_TAG: ${NOLUS_BUILDER_TAG}
    IMAGE_EXISTS_VARIABLE: NOLUS_BUILDER_EXISTS
    KANIKO_DOCKER_FILE: build/builder_spec
    KANIKO_IMAGE: ${NOLUS_BUILDER_IMAGE}
    KANIKO_IMAGE_EXISTS: NOLUS_BUILDER_EXISTS
  extends: 
    - .go-cache-vars
    - .image-exists
    - .kaniko

download-wasmvm-lib:
  stage: build
  image: "${NOLUS_BUILDER_IMAGE}"
  extends: .wasmvm-cache-vars
  cache:
    key: $WASMVM_CACHE_KEY
    paths:
      - $WASMVM_REL_DIR
  variables:
    WASMVM_LIB: "libwasmvm_muslc.a"
    WASMVM_URL: "https://github.com/CosmWasm/wasmvm/releases/download/v0.16.0/$WASMVM_LIB"
    WASMVM_LOCAL_PATH: $WASMVM_DIR/$WASMVM_LIB
  before_script:
    - mkdir -p $WASMVM_DIR
  script:
   - if [ ! -f "$WASMVM_LOCAL_PATH" ]; then wget -O $WASMVM_LOCAL_PATH $WASMVM_URL; fi

build-binary:
  stage: build
  extends:
    - .go-build
  script:
    - make build
  artifacts:
    paths:
      - target/release

build-image:
  stage: build
  needs: ["build-binary"]
  variables:
    IMAGE_REGISTRY_ID: ${AWS_REGISTRY_ID}
    IMAGE_REPO: ${NOLUS_NODE_REPO}
    IMAGE_TAG: ${NOLUS_NODE_TAG}
    IMAGE_EXISTS_VARIABLE: NOLUS_NODE_EXISTS
    KANIKO_DOCKER_FILE: build/node_spec
    KANIKO_IMAGE: ${NOLUS_NODE_IMAGE}
    KANIKO_IMAGE_EXISTS: NOLUS_NODE_EXISTS
  extends: 
    - .go-cache-vars
    - .image-exists
    - .kaniko

build-integration:
  stage: build
  needs: ["build-binary"]
  variables:
    IMAGE_REGISTRY_ID: ${AWS_REGISTRY_ID}
    IMAGE_REPO: ${NOLUS_INTEGRATION_REPO}
    IMAGE_TAG: ${NOLUS_INTEGRATION_TAG}
    IMAGE_EXISTS_VARIABLE: NOLUS_INTEGRATION_EXISTS
    KANIKO_DOCKER_FILE: build/integration_spec
    KANIKO_IMAGE: ${NOLUS_INTEGRATION_IMAGE}
    KANIKO_IMAGE_EXISTS: NOLUS_INTEGRATION_EXISTS
  extends: 
    - .go-cache-vars
    - .image-exists
    - .kaniko

test-fuzzer:on-schedule:
  extends: .go-test
  script:
    - make fuzz

test-unit-cosmos:on-schedule:
  extends: .go-test
  script:
    - make test-unit-cosmos

test-integration:
  stage: test
  image: "${NOLUS_INTEGRATION_IMAGE}"
  script:
    - make test-integration
